[project]
name = "fpldle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "curl-cffi>=0.12.0",
    "pandas>=2.3.1",
    "requests>=2.32.4",
    "understat>=0.1.4",
]
